[package]
authors      = ["Jiacheng"]
edition      = "2021"
license      = "MIT"
name         = "cc-switch-napi"
repository   = "https://github.com/botiverse/cc-switch-napi"
rust-version = "1.91.1"
version      = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
cc-switch   = { path = "vendor/cc-switch-cli/src-tauri" }
napi        = { version = "3.0.0", features = ["serde-json"] }
napi-derive = "3.0.0"
serde_json  = "1.0"

[build-dependencies]
napi-build = "2"

[profile.release]
lto   = true
strip = "symbols"
