/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Stateful access to CC Switch provider storage and live configuration.
 *
 * CC Switch reads its storage location from `CC_SWITCH_CONFIG_DIR`. Set that
 * environment variable before constructing this class when isolation is
 * required. Live application locations continue to follow the upstream
 * environment variables such as `CLAUDE_CONFIG_DIR` and `CODEX_HOME`.
 * Path selection is process-global; do not retarget environment variables
 * while an instance is active. Only one instance may exist per process.
 */
export declare class CcSwitch {
  /** Opens the current CC Switch store without importing live configuration. */
  constructor()
  /**
   * Closes the underlying store and releases the process-wide instance slot.
   *
   * Call this before deleting the store directory on Windows. Further method
   * calls on this object fail; constructing a new instance is allowed.
   */
  close(): void
  /** Returns every application supported by the vendored CC Switch core. */
  supportedApps(): Array<import('./api.js').AppId>
  /** Lists provider objects using the vendored CC Switch serialized shape. */
  listProviders(app: import('./api.js').AppId): Array<import('./api.js').Provider>
  /**
   * Returns the current provider id for switch-mode apps and Hermes.
   * OpenCode/OpenClaw are additive-mode apps and return `null`.
   */
  currentProvider(app: import('./api.js').AppId): string | null
  /** Adds a provider using fields supported by the vendored upstream revision. */
  addProvider(app: import('./api.js').AppId, provider: import('./api.js').Provider): boolean
  /** Replaces an existing provider by id. */
  updateProvider(app: import('./api.js').AppId, provider: import('./api.js').Provider): boolean
  /** Duplicates a provider, optionally applying an upstream-shaped override. */
  duplicateProvider(
    app: import('./api.js').AppId,
    sourceId: string,
    providerOverride?: import('./api.js').Provider | null | undefined,
  ): import('./api.js').Provider
  /** Switches the selected provider and, when initialized, writes its live config. */
  switchProvider(app: import('./api.js').AppId, providerId: string): void
  /** Deletes a provider. CC Switch refuses to delete an active provider. */
  deleteProvider(app: import('./api.js').AppId, providerId: string): void
  /** Imports providers from the application's current live configuration. */
  importLiveConfig(app: import('./api.js').AppId): number
  /**
   * Imports the current live config as the initial `default` provider.
   * Additive-mode apps return `false`; existing non-official providers are not overwritten.
   */
  importDefaultConfig(app: import('./api.js').AppId): boolean
  /** Removes a provider from an additive live config without deleting it. */
  removeFromLiveConfig(app: import('./api.js').AppId, providerId: string): void
  /** Sets the default provider/model for Hermes or OpenClaw. */
  setDefaultProvider(app: import('./api.js').AppId, providerId: string, modelId?: string | undefined | null): string
  /** Reads the application's live provider settings without changing them. */
  readLiveSettings(app: import('./api.js').AppId): import('./api.js').JsonValue
  /** Extracts a non-sensitive common-config snippet from the current provider. */
  extractCommonConfig(app: import('./api.js').AppId): string
  /** Extracts a non-sensitive common-config snippet from an arbitrary settings object. */
  extractCommonConfigFromSettings(app: import('./api.js').AppId, settings: import('./api.js').JsonValue): string
  /** Stores or clears the app-level common-config snippet used during provider writes. */
  setCommonConfig(app: import('./api.js').AppId, snippet?: string | undefined | null): void
  /** Clears the app-level common-config snippet. */
  clearCommonConfig(app: import('./api.js').AppId): void
  /** Writes all currently selected providers back to their live configs. */
  syncCurrentToLive(): void
  /** Returns applications that support MCP projection. */
  supportedMcpApps(): Array<import('./api.js').McpAppId>
  /** Lists the unified MCP server registry keyed by server id. */
  listMcpServers(): Record<string, import('./api.js').McpServer>
  /** Adds or replaces an MCP server and projects it to enabled applications. */
  upsertMcpServer(server: import('./api.js').McpServer): void
  /** Deletes an MCP server from the registry and every enabled live config. */
  deleteMcpServer(serverId: string): boolean
  /** Enables or disables one MCP server for one supported application. */
  toggleMcpApp(serverId: string, app: import('./api.js').McpAppId, enabled: boolean): void
  /** Replaces the complete application matrix for an MCP server. */
  setMcpApps(serverId: string, apps: import('./api.js').McpApps): boolean
  /** Projects enabled MCP servers to every supported app, or to one app. */
  syncMcpToLive(app?: import('./api.js').McpAppId | null | undefined): void
  /** Imports MCP servers from one supported app, or from every supported app. */
  importMcpFromLive(app?: import('./api.js').McpAppId | null | undefined): number
  /** Returns applications that support managed Skills. */
  supportedSkillApps(): Array<import('./api.js').SkillAppId>
  /** Lists installed managed Skills. */
  listSkills(): Array<import('./api.js').InstalledSkill>
  /** Installs a Skill from an upstream-supported spec and enables it for one app. */
  installSkill(spec: string, app: import('./api.js').SkillAppId): Promise<import('./api.js').InstalledSkill>
  /** Uninstalls a managed Skill from the SSOT and all application directories. */
  uninstallSkill(directoryOrId: string): void
  /** Enables or disables one installed Skill for one application. */
  toggleSkillApp(directoryOrId: string, app: import('./api.js').SkillAppId, enabled: boolean): void
  /** Replaces the complete application matrix for an installed Skill. */
  setSkillApps(directoryOrId: string, apps: import('./api.js').SkillApps): boolean
  /** Synchronizes enabled Skills to every supported app, or to one app. */
  syncSkillsToLive(app?: import('./api.js').SkillAppId | null | undefined): void
  /** Scans application directories for Skills not yet managed by CC Switch. */
  scanUnmanagedSkills(): Array<import('./api.js').UnmanagedSkill>
  /** Imports unmanaged Skills with an explicit per-Skill application matrix. */
  importSkills(selections: Array<import('./api.js').ImportSkillSelection>): Array<import('./api.js').InstalledSkill>
  /** Lists configured Skill repositories. */
  listSkillRepos(): Array<import('./api.js').SkillRepo>
  /** Adds or replaces a Skill repository. */
  upsertSkillRepo(repo: import('./api.js').SkillRepo): void
  /** Removes a Skill repository by owner/name. */
  removeSkillRepo(owner: string, name: string): void
  /** Returns the configured Skill deployment strategy. */
  skillSyncMethod(): import('./api.js').SkillSyncMethod
  /** Sets the Skill deployment strategy: auto, symlink, or copy. */
  setSkillSyncMethod(method: import('./api.js').SkillSyncMethod): void
  /** Discovers installable Skills from configured repositories. */
  discoverSkills(forceRefresh?: boolean | undefined | null): Promise<Array<import('./api.js').DiscoverableSkill>>
  /** Searches the skills.sh catalog using the vendored upstream client. */
  searchSkills(
    query: string,
    limit?: number | undefined | null,
    offset?: number | undefined | null,
  ): Promise<import('./api.js').SkillSearchResult>
  /** Checks installed repository-backed Skills for content updates. */
  checkSkillUpdates(): Promise<import('./api.js').SkillUpdateCheckResult>
  /** Updates selected installed Skills and reports per-Skill failures. */
  updateSkills(ids: Array<string>): Promise<import('./api.js').SkillUpdateBatchResult>
}
