/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Stateful access to CC Switch provider storage and live configuration.
 *
 * CC Switch reads its storage location from `CC_SWITCH_CONFIG_DIR`. Set that
 * environment variable before constructing this class when isolation is
 * required. Live application locations continue to follow the upstream
 * environment variables such as `CLAUDE_CONFIG_DIR` and `CODEX_HOME`.
 * Path selection is process-global; do not retarget environment variables
 * while an instance is active. Only one instance may exist per process.
 */
export declare class CcSwitch {
  /** Opens the current CC Switch store without importing live configuration. */
  constructor()
  /**
   * Closes the underlying store and releases the process-wide instance slot.
   *
   * Call this before deleting the store directory on Windows. Further method
   * calls on this object fail; constructing a new instance is allowed.
   */
  close(): void
  /** Returns every application supported by the vendored CC Switch core. */
  supportedApps(): Array<import('./api.js').AppId>
  /** Lists provider objects using the vendored CC Switch serialized shape. */
  listProviders(app: import('./api.js').AppId): Array<import('./api.js').Provider>
  /**
   * Returns the current provider id for switch-mode apps and Hermes.
   * OpenCode/OpenClaw are additive-mode apps and return `null`.
   */
  currentProvider(app: import('./api.js').AppId): string | null
  /** Adds a provider using fields supported by the vendored upstream revision. */
  addProvider(app: import('./api.js').AppId, provider: import('./api.js').Provider): boolean
  /** Replaces an existing provider by id. */
  updateProvider(app: import('./api.js').AppId, provider: import('./api.js').Provider): boolean
  /** Duplicates a provider, optionally applying an upstream-shaped override. */
  duplicateProvider(
    app: import('./api.js').AppId,
    sourceId: string,
    providerOverride?: import('./api.js').Provider | null | undefined,
  ): import('./api.js').Provider
  /** Switches the selected provider and, when initialized, writes its live config. */
  switchProvider(app: import('./api.js').AppId, providerId: string): void
  /** Deletes a provider. CC Switch refuses to delete an active provider. */
  deleteProvider(app: import('./api.js').AppId, providerId: string): void
  /** Imports providers from the application's current live configuration. */
  importLiveConfig(app: import('./api.js').AppId): number
  /**
   * Imports the current live config as the initial `default` provider.
   * Additive-mode apps return `false`; existing non-official providers are not overwritten.
   */
  importDefaultConfig(app: import('./api.js').AppId): boolean
  /** Removes a provider from an additive live config without deleting it. */
  removeFromLiveConfig(app: import('./api.js').AppId, providerId: string): void
  /** Sets the default provider/model for Hermes or OpenClaw. */
  setDefaultProvider(app: import('./api.js').AppId, providerId: string, modelId?: string | undefined | null): string
  /** Reads the application's live provider settings without changing them. */
  readLiveSettings(app: import('./api.js').AppId): import('./api.js').JsonValue
  /** Extracts a non-sensitive common-config snippet from the current provider. */
  extractCommonConfig(app: import('./api.js').AppId): string
  /** Extracts a non-sensitive common-config snippet from an arbitrary settings object. */
  extractCommonConfigFromSettings(app: import('./api.js').AppId, settings: import('./api.js').JsonValue): string
  /** Stores or clears the app-level common-config snippet used during provider writes. */
  setCommonConfig(app: import('./api.js').AppId, snippet?: string | undefined | null): void
  /** Clears the app-level common-config snippet. */
  clearCommonConfig(app: import('./api.js').AppId): void
  /** Writes all currently selected providers back to their live configs. */
  syncCurrentToLive(): void
}
